### ISSUE TITLE
For deploy on heroku

### ISSUE THREAD

**Issue by shazhir** [akasakaid/TiktokDownloader#1]
I have deployed it to heroku and put token into config file but bot won't response can you tell me steps to make the bot work and deploy it successfully

**Comment by akasakaid** [comment]
ok yeah, I haven't finished making readme.md

**Comment by shazhir** [comment]
> ok yeah, I haven't finished making readme.md

Dude i tried 
It worked
i put bot_polling into worker... instead bot_webhook
but i tried to use pyrogram librery to isntall broadcast method for bot but it won't work cuz when i uae broadcast commands other command of the bot like /start and recognize titkok link won't work
i did broadcast method to other bot files it doesn't getting error and stop! I think you can fix it 
And use another method isntead
bot_webhook and bot_polling
if you want example of my past bot to know how it worked even after i added broadcast method 
there it is : https://github.com/shazhir/shazhrtiktokdl
I think it is better to user another method isntead bot_webhook and bot_polling like any other bots...
thanks 😊❤❤

**Comment by akasakaid** [comment]
thanks for the advice, I haven't had time to fix my project
