### ISSUE TITLE
can not get id and hash

### ISSUE THREAD

**Issue by LDD123** [akasakaid/TiktokDownloader#19]
![Uploading 微信截图_20241013194433.png…]()

**Comment by LDD123** [comment]
![微信截图_20241013194433](https://github.com/user-attachments/assets/5e7a932a-3a43-4190-b1db-a44f3ce3b6c3)

**Comment by akasakaid** [comment]
This is not the place to ask that.

**Comment by LDD123** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
